server:
  port: 8080
  servlet:
    context-path: /gkcx/

mybatis:
  configuration:
    #mybatis插件开启mapper查询字段依据驼峰转成对象属性
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.lhcz.project.*.entity
  mapperLocations: classpath:mapper/*.xml
#mybatis分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true

spring:
  profiles:
    #使用配置文件
    active: dev
  thymeleaf:
    cache: false
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 3
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.mariadb.jdbc.Driver
    #一下为DruidDataSource参数
    # 初始化建立物理连接大小，默认0
    initialSize: 3
    #最小空闲连接数
    minIdle: 3
    #maxIdle:最大空闲数，已过时
    #允许最大连接数
    maxActive: 200
    #获取连接最大等待时间(毫秒)，等待的线程默认使用公平锁
    maxWait: 10000
    #useUnfairLock:false 使用非公平锁
    #保持连接池中一直有活动的连接
    keepAlive: true
    #和keepAlive=true配合使用，不能小于30000，默认值60000ms=1min
    keepAliveBetweenTimeMillis: 30000
    #用来检测连接是否有效
    validationQuery: select 1
    #申请连接时执行validationQuery检测连接是否有效，会降低点性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，会降低点性能
    testOnReturn: false
    #设置空闲时是否检测检测连接的可用性，不影响性能，且保证安全
    #如果连接空闲时间大于minEvictableIdleTimeMillis则关闭连接，直到连接数等于minIdle
    testWhileIdle: true
    #检测频率,默认值60*1000毫秒=1分钟，这里设置为1分钟
    timeBetweenEvictionRunsMillis: 60000
    #连接池中连接可空闲的时间,单位是毫秒，默认值30*60*1000=30分钟
    #maridb服务器端wait_timeout默认是600秒=10分钟，配合数据库的wait_timeout来设置该参数，这里设置2分钟
    minEvictableIdleTimeMillis: 120000
    #清理removeAbandonedTimeout秒没有使用的活动连接，从连接池移除
    #要求程序从池中get到连接后,N秒后必须close,否则druid会强制回收该，设置成true会抛出警告not use in productiion（生产环境不要用true)
    #removeAbandoned: true
    #druid强制回收时间，和removeAbandoned=true时配合使用，默认300*1000=5分钟
    removeAbandonedTimeoutMillis: 30000
    #数据库连接错误重连次数
    connectionErrorRetryAttempts: 3
    #数据库断开了会自动重连
    breakAfterAcquireFailure: true
    #断线重连的间隔-设置为5分钟
    timeBetweenConnectErrorMillis: 300000
    #初始化连接时执行语句
    connectionInitSqls: select 1
    #是否缓存preparedStatement即PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    #池中最多缓存preparedStatement的数量
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true

